name: cicd build    # Workflow Name
on:        
  push:
    branches:
      - main      # It's does which thing to do first like - when push on branch main 

jobs:
  build-and-deploy:            #after pushing on branch main, what job need to do. It will do build and deploy job which runs on ubuntu-latest server
    runs-on: ubuntu-latest     

    steps:
      - name : Checkout source code
        uses : actions/Checkout@v3  #This step clones your GitHub repo code into the runner (the temporary Ubuntu machine). Without this, the VM has no idea what your project is.

      - name : set up python
        uses : actions/setup-python@v5 
        with :
          python-version : '3.10'       # here we are setting up the python and it's version in ubuntu.
        
      - name : install dependencies
        run : pip install -r requirements.txt

      - name : login to the docker hub
        run : echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
        
      - name : Build docker image
        run : docker build -t ${{secrets.DOCKER_USERNAME}}/docker-portfolio-image .

      - name : Push to docker hub
        run : |
          docker tag docker-portfolio-image ${{secrets.DOCKER_USERNAME}}/docker-portfolio-image
          docker push ${{secrets.DOCKER_USERNAME}}/docker-portfolio-image

      - name : EC2 deployment
        uses : appleboy/ssh-action@v1.2.2
        with :
          host : ${{secrets.EC2_HOST}}
          username : ${{secrets.EC2_USER}}
          key : ${{secrets.EC2_SSH_KEY}}
          script :
            sudo apt upgrade -y
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/docker-portfolio-image
            sudo docker stop docker-portfolio-image || true
            sudo docker rm -f docker-portfolio-image || true
            sudo docker run -d -p 5001:5000 --name docker-portfolio-image ${{secrets.DOCKER_USERNAME}}/docker-portfolio-image